version: "3.9"

services:
  backend:
    container_name: fastapi-backend
    build:
      context: StudLicensing/backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./StudLicensing/backend/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - ./StudLicensing/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
