services:
  frontend:
    container_name: react-frontend
    image: node:23.9.0
    working_dir: /app
    volumes:
      - ./StudLicensing/frontend/app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TZ=Europe/Paris
      - REACT_APP_API_URL=http://localhost:8000
    command: >
      sh -c "npm install -g npm@latest && npm install && npm start"
    depends_on:
      - backend
      
  backend:
    container_name: fastapi-backend
    build:
      context: StudLicensing/backend/
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./StudLicensing/backend:/app
      - ./StudLicensing/uploads:/uploads
      - ./StudLicensing/logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - ./StudLicensing/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
