version: "3.9"

services:
  frontend:
    container_name: react-frontend
    image: node:23.9.0
    working_dir: /app
    volumes:
      - ./StudLicensing/frontend/app:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TZ=Europe/Paris
    command: >
      sh -c "npm install && npm start"

  backend:
    container_name: fastapi-backend
    build:
      context: StudLicensing/backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./StudLicensing/backend/app:/app
      - ./StudLicensing/uploads:/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:17.4
    env_file:
      - .env
    volumes:
      - ./StudLicensing/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
